# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Lanyon
tagline:          'Cures'
description:      'Acne Cure Zone features a number of brilliant resources that are curated and discussed in the Acne Cure Zone. Here you may find cures or at the least concise help written by people who have seen their acne resolved.'
url:              http://cures.lukeaslanian.com

author:
  name:           'Michael Aslanian'
  url:            https://acnecurezone.com

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/cures/cures.github.io
